config/routes.rb
Rails.application.routes.draw do

  # Static pages
  %w[license contact privacy terms].each do |page|
    get page, controller: 'info', action: page
  end

  devise_for :users
  resources :listings
  root 'home#index'
end

app/models/application_record.rb
# Abstract model ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background_check.rb
# Model for managing BackgroundChecks from Checkr
class BackgroundCheck < ApplicationRecord
  has_one :user
end

app/models/listing.rb
# Listing model to represent a property listing
class Listing < ApplicationRecord
  enum unit_type: [:feet, :meters, :acres]
  enum property_type: [
    :single_family,
    :condominuim,
    :townhouse,
    :multi_family,
    :land,
    :other
  ]

  has_one :user
  has_many :offers
  has_many :showings

  validates :address_line_one, :city, :state_id, :zip_code, presence: true
end

app/models/offer.rb
# Model that represents a property listing offer
class Offer < ApplicationRecord
  enum deed_type: [
    :warranty,
    :special_warranty,
    :quit_claim,
    :bargain_and_sale,
    :grant
  ]

  has_one :user
  has_one :listing
end

app/models/showing.rb
# Model for a Property Showing
class Showing < ApplicationRecord
  enum showing_type: [:open, :closed]

  has_one :user
  has_one :listing
end

app/models/state.rb
# Model for US states
class State < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/user.rb
# A model for a site user
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  has_many :listings
  has_many :showings
  has_one :background_check
end

app/controllers/application_controller.rb
# Base ApplicationController for extension
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# HomeController for managing landing page
class HomeController < ApplicationController
  def index; end
end

app/controllers/info_controller.rb
# InfoController for rendering a few static assets
# that need ruby
class InfoController < ApplicationController
  def license; end

  def contact; end

  def privacy; end

  def terms; end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.fetch(:listing, {})
            .permit(
              :address_line_one,
              :address_line_two,
              :address_line_three,
              :city,
              :state_id,
              :county,
              :zip_code)
    end
end

app/helpers/application_helper.rb
# Helper methods application wide
module ApplicationHelper
end

app/helpers/home_helper.rb
# Helper methods for home page
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/info/privacy.html.erb
<h1>Privacy policy</h1>

app/views/layouts/_flash_messages.html.erb
<div id="flash-messages" class="container">
    <% if flash[:notice] %>
        <div class="row alert alert-success" role="alert"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
        <div class="row alert alert-danger" role="alert"><%= flash[:alert] %></div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyleft"><span class="symbol">&copy;</span> <%= Date.today.year %> Elistair</div>
  <div class="links">
    <ul>
      <li><%= link_to 'Terms', terms_path %></li>
      <li><%= link_to 'License', license_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      <li><%= link_to 'Privacy', privacy_path %></li>
      <li><a href="https://gitlab.com/Elistair" target="_blank">Code</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">
        <img src="" alt="Elistair logo">
      </a>
    </div>
    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, :class => 'btn btn-link navbar-btn navbar-right', :method => :delete %> 
    <% else %>
      <%= link_to 'Sign in', new_user_session_path, :class => 'btn btn-primary navbar-btn navbar-right' %>
      <%= link_to 'Register', new_user_registration_path, :class => 'btn btn-link navbar-btn navbar-right' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
    Elistair, The freest real estate community in the world
    Copyright (C) 2016  Evan E. Duncan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<html>
  <head>
    <title>Elistair</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <section class="container" id="content"><%= yield %></section>
    <%= render 'layouts/footer' %>
  </body>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= f.text_field :address_line_one, class: 'form-control', placeholder: 'Street' %>
    </div>

    <div class="form-group">
      <%= f.text_field :address_line_two, class: 'form-control', placeholder: 'Unit, suite, etc.' %>
    </div>

    <div class="form-group">
      <%= f.text_field :city, class: 'form-control', placeholder: 'City' %>
    </div>

    <div class="form-group">
      <%= %>
    </div>

    <%= f.submit 'Create', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>